version: '3'

services:
  nodejs:
    build: 
      context: ./docker/nodejs
    container_name: todo-nodejs
    environment:
      # application environment variables
      - DB_HOST=127.0.0.1
      - DB_USER=root
      - DB_PASSWORD=
      - DB_DATABASE=tododb
      - PORT=1350
      - NODE_ENV=alterdb
    volumes:
      # mount our directory to the working_dir
      -./todo-application/todo-server:/home/node/todo-server
    expose:
      - "1350" #expose the application port
    command: "node app.js"