version: '3'

services:
  nodejs:
    build: 
     context: .
     dockerfile: ./docker/nodejs/Dockerfile
    container_name: todo-nodejs
    environment:
      # application environment variables
      DB_HOST: 127.0.0.1
      DB_USER: todoserver
      DB_PASSWORD: todoserverpassword
      DB_DATABASE: tododb
      PORT: 1350
      NODE_ENV: alterdb
 
    #volumes:
      # mount our directory to the working_dir
      #- ./todo-application/todo-server:/todo-server
      #- ./todo-application/todo-server/node_modules:/todo-server/node_modules
    # expose:
    #   - "1350" #expose the application port
    ports: 
      - "1350:1350"
    command: "npm start"
    depends_on: 
      - "db"
  db: 
    image: mariadb:10.3.7
    container_name: "todo-nodejs-mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: "todoserver"
      MYSQL_PASSWORD: "todoserverpassword"
    volumes:
      - database:/var/lib/mysql
      - ./bin/db_setup.sh:/docker-entrypoint-initdb.d/db_setup.sh
      - ./docker/mysql/db_user.sql:/docker-entrypoint-initdb.d/db_user.sql
volumes:
  database:
#   - ./todo-application/todo-server:/todo-server